# Generated by Django 4.1.4 on 2023-01-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Featured',
        ),
    ]
